### ISSUE TITLE
Is Rapid CMS Client Side a good fit for targeting an existing REST API?

### ISSUE THREAD

**Issue by TheColonel2688** [ThomasBleijendaal/RapidCMS#161]
The ERP software we use at work has a REST API. I am wanting to extend it using that API to add additional "Reports" and bulk actions that their provided Client does not have.

There Server is closed source but the API is decently Documented. 

Is this a good fit for Client Side RapidCMS? Or would it be too cumbersome?

P.S. I did not see a link to a separate Discussion  area. If their is a better place to ask question please direct me there.

**Comment by ThomasBleijendaal** [comment]
I would say yes, but it depends on a few things. 

The biggest issue is I think security when running a front-end RapidCMS. If you don't have to keep something like an API key secret, or if you don't care, you could run everything front-end. If you need to keep the API key secret and need to run something on a web server, why not run RapidCMS on that web server.

If the API supports simple CRUD action on their entities you could get pretty far with it. You'd need to implement repositories that map the repository actions to API calls and serialize and deserialize their api models to entities. If you want to trigger some bulk actions you could build some custom button handlers and/or button panes to trigger those actions. You can control which buttons you want to show on the views and editors, so if the API does not support some repository action you can just leave it out and also not implement it in the repository.

Furthermore, it also depends on whether the API allows you to do that. I've found, when I was building a custom frontend for Azure KeyVault, that if the API does not have a CORS policy than it becomes quite the challenge. I've solved that by running the blazor front-end in a [MAUI wrapper](https://github.com/ThomasBleijendaal/RapidCMS/blob/master/SETUP_MAUI.md) and have it run as 'native' application which doesn't need CORS. You can see my approach in this repo: https://github.com/ThomasBleijendaal/Vaultr. It is also somewhat of a difficult example as I wanted a really flexible CMS so everything is implemented as a plugin, which requires quite some knowledge on the internal workings of RapidCMS.

**Comment by TheColonel2688** [comment]
> The biggest issue is I think security when running a front-end RapidCMS. If you don't have to keep something like an API key secret, or if you don't care, you could run everything front-end. 
There is a simple authentication exchange on login, this is not exactly a first-class API, you send a user name and password, and respond with an authentication token for the session. 

then all subsequent API requests you just need to insert the "Authentication" header in with `$"Bearer {token}"`.

> need to run something on a web server, why not run RapidCMS on that web server.
maaaaaaay, but I am not sure what approach to take. I will probably eventually want to have my women repo to store extra data, like user preferences etc. Maaaaaaybe extended the data that is stored on their server/db.

Should run RapidCMS serverside and relay calls to their API through it, or just have the client talk directly to their API. 

At this point running everything through my own server just seems like it would be redundant and just add work for myself.

or do you mean that if I need to run my own RapidCMS server, I should just do it on the same server? In that case that is probably what I would do. Our ERP Server software just runs on a Windows 10 VPS.

But I am a noob when it comes to this stuff, most of my experience is writing process automation code to interact and control various industrial equipment from .Net Services or Desktop Apps. I am very familiar with the C# language but architecture outside of that use case is just all hypothetical to me right now.

> that if the API does not have a CORS policy then it becomes quite the challenge.
I do not think that will be an issue. Everything in evolved with the 

Can you point me at any relvent docs or samples that would be as close to what I am doing as possible?

**Comment by ThomasBleijendaal** [comment]
The authentication point sounds like it is not going to be any problem. You can create a LoginScreen component where you can ask for a user name and password, use those to get the token and store that somewhere in the session storage. If you derive from AuthenticationStateProvider you can use that class to check whether a token has been saved in the session storage, and that way you can indicate whether the user has been logged in, or still needs to login. RapidCMS does the rest for you then. I haven't got any good documentation on this, but you can look at the https://github.com/ThomasBleijendaal/RapidCMS/blob/master/src/RapidCMS.Core/Authorization/AnonymousAuthenticationStateProvider.cs to see a base implementation. Core idea is that once the ClaimsPrincipal has any claims, the user is considered logged in. Its all asp.net core stuff so you can find quite some documentation on that.

I would focus on getting the repository working with the API. You will need that code anyway and you can quickly discover whether a pure front-end approach is going to work. Resolving the session token in the repositories is not that difficult, you just need to fetch if from the session storage when you make an API call in the repository.

The biggest challenge you can encounter with this is probably CORS. If your ERP API runs on api.erp.com and your client-side RapidCMS runs on erpcms.something.tld then it could be that the api.erp.com CORS settings do not allow browsers to make calls to that domain from erpcms.something.tld. 

If that happens than you need a little server-side companion that will access the ERP API, and that willl run under erpcms.something.tld. If your ERP API already runs under the same domain as where your cms is hosted then everything is fine, and any browser will be happy.

But once you are at that point then you can ask yourself whether that approach is the most simple: if you started out with a simple client side only CMS that just talks with an API, but end up with two things, the static CMS, and a proxy API companion that does all the talking to the ERP. The username and password you store on the frontend needs to make its way to the proxy API, and you get in quite a lot of added complexity. Then you could ask yourself why not switch to server-side CMS, in which blazor server-side does all the browser handing and you just implement the repositories that talk to the API on the server.

Both approaches require you to first implement the repositories, so it's not like that you have to choose immediately, you might just have to convert from client-side to server-side RapidCMS, but that isn't much of a problem.

**Comment by TheColonel2688** [comment]
Thank you for all your help. I appreciate it.

**Comment by TheColonel2688** [comment]
Why does clicking on the Collection name on the side menu call NewAsync? I would expect it to call GetAllAsync

Is NewAsync intended as a new or default view? is that the idea?

**Comment by TheColonel2688** [comment]
Side Note: Could you add Method comments to IRepository?

**Comment by ThomasBleijendaal** [comment]
I can add comments to `IRepository`, but for now please look at https://github.com/ThomasBleijendaal/RapidCMS/blob/master/src/RapidCMS.Core/Repositories/BaseRepository.cs. That base has most of the methods documented, and the developer experience is better when deriving from that base instead of starting from scratch with a IRepository.

**Comment by TheColonel2688** [comment]
> The NewAsync is called to get an empty model that is given to the authorization handler. The auth model Resource Based (https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-6.0) so that needs a concrete model. The GetAll could potentially return nothing, I use the NewAsync to get at least one.
> 
> It does not have to be an entity that exists anywhere, it can simply be a new instance with Id = null.

hmmm I swear I tried returning a new empty instance of my entity, I will try it again.

What calls GetAllAsync? I am just trying to figure out how to get a default view of my list to appear. Is Something called after NewAsync?

> I can add comments to `IRepository`, but for now please look at https://github.com/ThomasBleijendaal/RapidCMS/blob/master/src/RapidCMS.Core/Repositories/BaseRepository.cs. That base has most of the methods documented, and the developer experience is better when deriving from that base instead of starting from scratch with a IRepository.

Hmm ok, so I should instead drive from BaseRepository. I will give it a try thank you.

**Comment by TheColonel2688** [comment]
So far so good, this is just a side project so I work on it in little bursts. When I have time.

I am sure I will have more questions later.

Thank you for all your help

I'll close this for now
