### ISSUE TITLE
Server Side Setup .md needs updated?

### ISSUE THREAD

**Issue by TheColonel2688** [ThomasBleijendaal/RapidCMS#162]
I am moving all of my code so far over to a Server Side project, this tripped me up though. (For better debugging)

https://github.com/ThomasBleijendaal/RapidCMS/blob/master/SETUP_SERVERSIDE.md

> Replace the <link href="css/site.css" rel="stylesheet" /> tags in _Host.cshtml with <link href="_content/RapidCMS.UI/css/site.css" rel="stylesheet" /> and remove any other css. Add <script src="_content/rapidcms.ui/js/interop.js"></script> at the end of the body tag.

Should that actually be in _Layouts.cshtml for a Server project?

That line doesn't exist in _Host.cshtml in a new Server project.

Did they change the template since you made the instructions?

**Comment by ThomasBleijendaal** [comment]
_Layouts.cshtml sounds like you have created a ASP.NET MVC project, for which I haven't written the server side documentation. You could try to create a ASP.NET Razor Pages project, which will have a _Host.cshtml. 

I'll probably need to make the documentation better, or try adding RapidCMS to a MVC project and see what is needed there.

**Comment by TheColonel2688** [comment]
When I get home today I will double-check that I used the correct template.

**Comment by TheColonel2688** [comment]
I just created a fresh test of the Blazor Server App template. and it does indeed have a _Layout.cshtml in it.

![image](https://user-images.githubusercontent.com/8753759/153692325-74cdca7e-4fbf-4243-9008-4cafc05b9a9b.png)
![image](https://user-images.githubusercontent.com/8753759/153692339-20b1f891-f345-41cf-940b-335e562bd5c3.png)
