### ISSUE TITLE
Can't install RapidCMS.Repositories package

### ISSUE THREAD

**Issue by mcintyre321** [ThomasBleijendaal/RapidCMS#195]
Interesting project. I can't follow the guide thought, becuase the nuget package for `RapidCMS.Repositories` depends on `RapidCMS.Example.ModelMaker.Models (>= 4.9.0)` which isn't on Nuget. Are you able to update it please?

**Comment by ThomasBleijendaal** [comment]
Whoops, that's a mistake. I've created a fix for that and update the packages after I've merged that.
