### ISSUE TITLE
Using the generic method 'ICmsConfig.AddCollection<TEntity, TRepository>(string, string, Action<ICollectionConfig<TEntity>>)' requires 2 type arguments

### ISSUE THREAD

**Issue by orthoxerox** [ThomasBleijendaal/RapidCMS#40]
The example on the front page `config.AddCollection<Person>("person", "Person", collection => ...` no longer compiles in 3.1.8.

**Comment by ThomasBleijendaal** [comment]
Good catch, the method now requires the repository, so something like: `.AddCollection<Person, InMemoryRepository<Person>>( ..` should work. I'll update the docs with the latest changes.

**Comment by orthoxerox** [comment]
If you're updating them, then `AddRapidCMS` should now be `AddRapidCMSServer` for the server-side configuration.

**Comment by ThomasBleijendaal** [comment]
Yeah, I'm going to do a full sweep of the documentation. I wrote that a while back, and it shows.
