### ISSUE TITLE
Custom context root?

### ISSUE THREAD

**Issue by Filiecs** [ThomasBleijendaal/RapidCMS#73]
I have been trying out RapidCMS and it seems pretty sweet. However, I'd like to add it onto an existing web application, just at a different context root. For example, my website is 'mysite.net' but I would like the dashboard for RapidCMS to be at 'mysite.net/admin'.
I was able to get the routing setup as follows:
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapBlazorHub();
    endpoints.MapFallbackToPage("/Admin", "/Admin/RapidCMS");
    endpoints.MapFallbackToPage("/_Host");
    endpoints.MapControllers();
});
```
Admin/RapidCMS.cshtml is essentially the same as a _Host.cshtml configured for RapidCMS that then runs the RapidCmsRouter component, like normal.

When I visit the page, however, I am greeting with RapidCMS's 'There's nothing here' page.
If I reverse the routing, and have RapidCMS at the root and my website under /Admin, however, it works fine.

Is there currently any way to change the context root?

**Comment by ThomasBleijendaal** [comment]
I haven't really tested this out yet, but I think it should be something that RapidCMS should support. I did some [tests](https://github.com/ThomasBleijendaal/RapidCMS/commit/030aafdcceaf46b9bfb0309180b2e6b2ab798a5b) and found that if you configure the startup as following I got RapidCMS running under `/admin` instead of `/`. 

```cs
app.UsePathBase("/Admin");

app.UseEndpoints(endpoints =>
{
    endpoints.MapBlazorHub();
    endpoints.MapBlazorHub("/admin/_blazor");
    endpoints.MapFallbackToPage("/Admin/{**path:nonfile}", "/Admin/RapidCMS");
    endpoints.MapFallbackToPage("/_Host");
});
```

**Comment by Filiecs** [comment]
Thanks for the response, that worked. I just had to add "../" before the .css and .js paths as well.
