### ISSUE TITLE
Update docs for version 4.0 to really demonstrate what is possible with RapidCMS

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ThomasBleijendaal/RapidCMS#93]

**Comment by TheColonel2688** [comment]
Yes I would really like to know more about the new model maker. I've only read some commit descriptions but it seems we can dynamically create models in the UI now?

Really looking for a very low code relational CMS that allows me to augment and extend where ever I need to.

I've been watching the project almost since it started and this seems really exciting to me.

**Comment by ThomasBleijendaal** [comment]
Yeah that's right. If you check out https://github.com/ThomasBleijendaal/RapidCMS/tree/model-maker-feature-complete, have a Azure Storage Emulator running and start run the RapidCMS.Example.ModelMaker project you could see at what it is. 

The idea is that it's something like Umbraco or Contentful where you can make your own models in the CMS itself. I do see some challenges with how to get a working database behind it. I'm thinking using a Source Generator which maps the configuration to actual models had generate a EF Core DbContext and/or MongoDB database based on what is configured in the model maker. So you have flexibility when developing but when deploying your application it's all based on concrete models and as fast as possible.

**Comment by TheColonel2688** [comment]
Are migrations on your road map so we can use this interface to evolve the model over time on a production instance? Or will it be one shot done and any changes have to be done manually in code?

**Comment by ThomasBleijendaal** [comment]
I think migrations must be a key part of this system, because nothing is more a hassle than managing model updates in a CMS, especially between environments (like test and production). But I don't want to really build it myself, so I was thinking that if the CMS can generate a working EF Core DbContext, then the migrations can be created using EF Core tools. If a model is updated in the CMS, it's corresponding entity changes, and EF Core can generate a migration for it.

Having a generated DbContext also makes building an API / website based on the CMS data a lot easier. Currently the entire model is put in a JSON and that gets saved in the database, which is a poor developer experience, and implementing things like a simple search is almost impossible. A DbContext with concrete models makes building logic a lot easier, and saves me from making an API to get the model maker data out of the CMS.

The CMS that will run on a production instance will not be the model maker itself, but the generated RapidCMS based on what was made with the model maker. The shape of the CMS and models will be read-only, but very performant because everything is concrete and no heavy JSONs or reflection is required anymore.

**Comment by ThomasBleijendaal** [comment]
I've updated the documentation to include a install guide (https://github.com/ThomasBleijendaal/RapidCMS/blob/master/SETUP_MMSERVERSIDE.md) and quick start (https://github.com/ThomasBleijendaal/RapidCMS/blob/master/MMQUICKSTART.md) for the model maker plugin.

This should be enough to get an idea of what it is and how to set it up. If you have any questions, you can reopen this issue or create a new one.
